### ISSUE TITLE
"将docSet.dsidx内容导出到sqlite中" 的疑问

### ISSUE THREAD

**Issue by liangzcn** [NetEaseGame/iOS-private-api-checker#11]
请问 “将docSet.dsidx内容导出到sqlite中” 它的具体操作是什么呢？我尝试用文本编辑， 但是打不开， Navicat也不行，请问这句话的细节操作是什么呢？希望能清晰一点，萌新不太会操作。。

**Comment by vbonluk** [comment]
+1
