### ISSUE TITLE
提示说可能不是ipa文件

### ISSUE THREAD

**Issue by fantasysea** [NetEaseGame/iOS-private-api-checker#5]
提示说可能不是ipa文件。这是什么意思呢？
还有我发现config.py下面有mysql相关的东西，不是说使用sqlite的吗
mysql_info 这个需要配置吗？

**Comment by hustcc** [comment]
参考一下 #1

**Comment by fantasysea** [comment]
好的,谢谢,可以运行了,.但是还是不明白mysql哪里用到了?

**Comment by hustcc** [comment]
最早用的 mysql 存储，后来迁移的时候，为了部署方便就换成了 sqlite。

**Comment by fantasysea** [comment]
好的，明白了
